#!/usr/bin/env bash
# This script generates a MySQL dump and creates a compressed archive from it
mysqldump -u root -p"$1" --all-databases > backup.sql
curr_date=$(date +"%d-%m-%Y")
tar -czf "$curr_date".tar.gz backup.sql
